apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: margocd

resources:
- github.com/argoproj/argo-cd/manifests/ha/cluster-install?ref=v2.6.7&timeout=90s

patches:
  - path: ../patches/argocd-cm.yaml
  - path: ../patches/argocd-server-service.yaml
  - path: ../patches/argocd-cmd-params-cm.yaml
  - target:
      kind: ClusterRole
      labelSelector: "app.kubernetes.io/name=argocd-server"
    patch: |-
      - op: replace
        path: /metadata/name
        value: margocd-server
  - target:
      kind: ClusterRoleBinding
      labelSelector: "app.kubernetes.io/name=argocd-server"
    patch: |-
      - op: replace
        path: /metadata/name
        value: margocd-server
      - op: replace
        path: /subjects/0/namespace
        value: margocd
  - target:
      kind: ClusterRole
      labelSelector: "app.kubernetes.io/name=argocd-application-controller"
    patch: |-
      - op: replace
        path: /metadata/name
        value: margocd-application-controller
  - target:
      kind: ClusterRoleBinding
      labelSelector: "app.kubernetes.io/name=argocd-application-controller"
    patch: |-
      - op: replace
        path: /metadata/name
        value: margocd-application-controller
      - op: replace
        path: /subjects/0/namespace
        value: margocd
