apiVersion: v1 
kind: ConfigMap 
metadata: 
  name: argocd-cm 
data: 
  timeout.reconciliation: 300s
  configManagementPlugins: |
    - name: kustomize-enable-helm
      generate:
        command: [ "sh", "-c" ]
        args: [ "kustomize build --enable-helm" ]
